### ISSUE TITLE
Bug: flickering and pausing as the macro icons refresh

### ISSUE THREAD

**Issue by caewok** [earlSt1/vtt-macro-folders#15]
Foundry 0.7.9, macro folders 1.1.1, dnd5e 1.2.4. 
Running server on https://github.com/felddy/foundryvtt-docker on a Vultr VM.
Using Firefox 88.0.

When I add or edit a macro from the macro folder (with the list of macros on the screen), it causes a refresh of the macro list whereby all the macro icons flicker repeatedly. During this refresh, I cannot search in the macro list or click or right-click the macros in the list. In effect, the refresh causes the macro list to freeze until it is done. This can take upwards of 10 seconds. (I have quite a few macros, plus the ones that get automatically created whenever I or a player drag a weapon to the hotbar.) 

I would classify this as a bug, because it may be due to code that is locking unnecessarily. Maybe an update that is running sequentially instead of updating all at once? My laptop is rather old, so it may be more noticeable for me than others. 

Thanks for the module; it is very useful!

**Comment by earlSt1** [comment]
Thanks for raising this, I've experienced it once during testing and someone else has also raised it. I've been busy the past week but hopefully will be able to sort it out by the weekend :smile:

**Comment by earlSt1** [comment]
Hi, i've improved the rendering for the macro directory, so it shouldn't refresh as much (it should cut it by at least half). Would you be able to give it a test by uninstalling your current version of macro folders and installing this one using the manifest text option in the install screen:

https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/master/test/module.json

**Comment by caewok** [comment]
Yes, it seems much better in the test version. Thanks!
