### ISSUE TITLE
Error in 0.8.5 not import macros

### ISSUE THREAD

**Issue by rinnocenti** [earlSt1/vtt-macro-folders#16]
Not import macros, and  error on create new macros.
![image](https://user-images.githubusercontent.com/3178127/119239913-d7e01080-bb22-11eb-9b0e-ca7a5e694c27.png)

**Comment by earlSt1** [comment]
Thanks for raising this, i think i found the problem. Can you try installing using this testing manifest and trying again?

https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/08x-update/test/module.json

**Comment by rinnocenti** [comment]
Work in parts 

when I create a macro directly from the macro bar, the macro does not appear in the macro folder.
The Macro is editable, and work, but no show in folder.

![image](https://user-images.githubusercontent.com/3178127/119248483-d5ec7080-bb67-11eb-826f-da8d61110f7e.png)

**Comment by earlSt1** [comment]
Ok, ill look into it properly today. As you said its just a rendering issue, so if you close the directory and open it it should appear (hitting the refresh button to the left of the search bar might make it appear too)

**Comment by earlSt1** [comment]
Can you try again by uninstalling and installing via the manifest above again?

**Comment by rinnocenti** [comment]
its work!

**Comment by earlSt1** [comment]
Great thanks, fix included in v1.2.1 if you update it will get the new version :)
