### ISSUE TITLE
Bug: when trying to import a complete compendium with "import all content" - works when macro folders is disabled [foundry 0.8.6]

### ISSUE THREAD

**Issue by spirritus** [earlSt1/vtt-macro-folders#17]
Uncaught (in promise) ReferenceError: assignment to undeclared variable folderId
    defineClasses macro-folders.js:884
    call_wrapper libWrapper-wrapper.js:558
    0 libWrapper-wrapper.js:145
    yes foundry.js:33385
    callback foundry.js:20407
    submit foundry.js:20351
    _onClickButton foundry.js:20314
    jQuery 9
    activateListeners foundry.js:20299
    _render foundry.js:2069
    call_wrapped libWrapper-wrapper.js:449
    <anonymous> libWrapper-errors.js:268
    0 libWrapper-wrapper.js:143
    render foundry.js:2003
    confirm foundry.js:20427
    confirm foundry.js:20398
    callback foundry.js:33380
    callback compendium-folders.js:856
    render foundry.js:20148
    jQuery 7
        dispatch
        handle
        add
        Ee
        each
        each
        Ee
macro-folders.js:884:9
    callback compendium-folders.js:859
    AsyncFunctionThrow self-hosted:699
    (Async: async)
    render foundry.js:20148
    jQuery 9
    render foundry.js:20145
    bind foundry.js:20088
    jQuery 8
    bind foundry.js:20076
    ContextMenu foundry.js:20057
    _contextMenu foundry.js:23803
    activateListeners foundry.js:23515
    activateListeners compendium-folders.js:752
    _render foundry.js:2069
    AsyncFunctionNext self-hosted:695
    (Async: async)
    call_wrapped libWrapper-wrapper.js:449
    call_wrapped self-hosted:1282
    <anonym> libWrapper-errors.js:268
    wrapper self-hosted:1225
    0 libWrapper-wrapper.js:143
    _render foundry.js:23127
    _render df-scene-enhance.js:3
    next self-hosted:1433
    fulfilled df-scene-enhance.js:3
    (Async: promise callback)
    step df-scene-enhance.js:3
    fulfilled df-scene-enhance.js:3
    (Async: promise callback)
    step df-scene-enhance.js:3
    fulfilled df-scene-enhance.js:3
    (Async: promise callback)
    step df-scene-enhance.js:3
    fulfilled df-scene-enhance.js:3
    (Async: promise callback)
    step df-scene-enhance.js:3
    fulfilled df-scene-enhance.js:3

​

**Comment by earlSt1** [comment]
Gah, I fixed this in 0.7.10, forgot to merge it into 0.8.6. 

Can you try again by uninstalling Macro Folders and installing using this testing manifest? https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/08x-update/test/module.json

**Comment by spirritus** [comment]
Jo, looks good. But the compatibility is still set for 0.8.5. ;-)

**Comment by earlSt1** [comment]
Fix included in v1.2.2 (and bumped compatibility as well 😄)
