### ISSUE TITLE
Macro Directory loads on scene when no scene is selected.

### ISSUE THREAD

**Issue by Koalahund** [earlSt1/vtt-macro-folders#19]
After loading the world or whenever there is no active scene selected the macro directory loads in the background/as scene (see screenshot at the top).

![48f0f4fa50c3f94c901653a311b84e96](https://user-images.githubusercontent.com/85458282/121029111-9d27da80-c7a8-11eb-90a3-768aaf25d78d.png)

Foundry Version 0.8.6
Pathfinder 1 0.78.8
Active Modules: Macro Folders and libWrapper

**Comment by earlSt1** [comment]
Oh wow, that looks horrible :smile:

I'll see if i can replicate this at some point, thanks for the report!

**Comment by earlSt1** [comment]
Yep, seems to be no active scene causes this weird issue. I've been moving house and have just finished hooking up my internet + PC, so I can check this out tomorrow.

**Comment by earlSt1** [comment]
Hi so i think i may have fixed this. Can you try by uninstalling your current MF and installing this one using the manifest: https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/08x-update/test/module.json

**Comment by Koalahund** [comment]
Hey, 
sry, wasn't checking for updates 
ye that version works without problems so far, thank you :)

**Comment by earlSt1** [comment]
Thanks, I'll keep this issue open as its not in the main release branch yet, when it is ill close it again :smile:

**Comment by earlSt1** [comment]
Fixed in v1.2.21
