### ISSUE TITLE
Incorrectly Translated Menu?

### ISSUE THREAD

**Issue by tjlanza** [earlSt1/vtt-macro-folders#22]
Foundry 0.8.7, MF 1.2.2, libWrapper 1.7.1.0

I suspect the name of the last menu item shown below is something that's supposed to be translatable, but has gone awry.

![image](https://user-images.githubusercontent.com/21128724/122582094-bee55500-d025-11eb-8929-db90021c3b39.png)

**Comment by earlSt1** [comment]
Ahhh, well spotted! I forgot to change the translation code from Compendium Folders to Macro Folders (and in testing i usually have both enabled)

This will be fixed in the next release :smile:

**Comment by earlSt1** [comment]
Fixed in v1.2.21
