### ISSUE TITLE
Feature Suggestion: Sidebar Macros integration

### ISSUE THREAD

**Issue by ravingdragoon** [earlSt1/vtt-macro-folders#30]
It would be really cool if this module worked with the Sidebar Macros module to put foldered modules in the sidebar.

**Comment by earlSt1** [comment]
Good news, this is almost here, just waiting on arcanistzed to commit the changes needed, then i'll commit mine:
![mf_sidebar](https://user-images.githubusercontent.com/13738280/134090733-238f6653-fd94-456f-bc07-05f0bf257537.gif)

**Comment by ravingdragoon** [comment]
Any news on this? Here is the related post on Sidebar Macros https://github.com/arcanistzed/sidebar-macros/issues/2#issue-989966648
