### ISSUE TITLE
Feature req: When importing a macro compendium, create the folder and place them inside

### ISSUE THREAD

**Issue by sharkbruhaha** [earlSt1/vtt-macro-folders#5]
When importing from a compendium, it asks you for a folder name. Please make that folder as a macro folder and place the importing macros into that folder.

**Comment by earlSt1** [comment]
Oooh thats something I hadn't even considered. I can absolutely look into that as part of compendium folders once i've finished tidying it up :D

**Comment by earlSt1** [comment]
Feature now partially included with the Compendium Folders integrations in version 1.0.8 (you need to use the export function provided by Compendium Folders, the Import All provided by foundry probably wont work)

I'll see about including support for the Import All thing next version.

Edit: I misunderstood the request. There's another issue open for this feature now (#6)
