### ISSUE TITLE
button to import macros

### ISSUE THREAD

**Issue by rinnocenti** [earlSt1/vtt-macro-folders#7]
I have a problem.

in my old worlds the button to import macros for compendium works (they appear in all folders).

however in new worlds (created in Fvtt 0.7.9) the button not displayed.
Even with only two active folder modules.

NO error in Console

![image](https://user-images.githubusercontent.com/3178127/104404983-b5b60080-553a-11eb-9143-bc08e804bb61.png)

**Comment by earlSt1** [comment]
This is something I forgot to add to the readme, but if you dont have any valid compendiums to export to (unlocked macro ones), then the buttons will not appear. 

If you create a valid compendium and close+open the directory they should appear. I'll see about changing this to match the previous functionality soon
